import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      ><nav className="grid grid-cols-1 grid-rows-2 items-center justify-center px-15 border-solid border-4 rounded-xl border-amber-400 text-amber-400 lg:grid-cols-2 lg:grid-rows-1 lg:justify-between lg:p-6 lg:px-16">
          <h3 className="font-semibold text-4xl mx-auto lg:text-5xl lg:m-0">MOHAIMINUL ISLAM</h3>
          <div className="grid grid-cols-1 grid-rows-1 items-center justify-center">
            <ul className="grid grid-cols-4 items-center justify-center">
              <li className="grid grid-cols-1 items-center justify-center mx-auto">
                <a href="#" className="text-xl hover:text-orange-600 font-semibold">About</a>
              </li>
              <li className="grid grid-cols-1 items-center justify-center mx-auto">
                <a href="#" className="text-xl hover:text-orange-600 font-semibold">Skills</a>
              </li>
              <li className="grid grid-cols-1 items-center justify-center mx-auto">
                <a href="#" className="text-xl hover:text-orange-600 font-semibold">Projects</a>
              </li>
              <li className="grid grid-cols-1 items-center justify-center mx-auto">
                <a href="#" className="text-xl hover:text-orange-600 font-semibold">Contact</a>
              </li>
            </ul>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
